#!/usr/bin/env python3
import sys
import subprocess
import os.path

_root_dir = os.path.abspath(os.path.dirname(__file__))

sys.exit(subprocess.call([
    'kubectl',
    '--kubeconfig',
    'production.ethereum-1.kubeconfig',
] + sys.argv[1:]))
