---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bootnode
  labels:
    component: bootnode
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bootnode
  template:
    metadata:
      labels:
        component: bootnode
    spec:
      containers:
        - name: bootnode
          image: 'ethereum/client-go:alltools-v1.8.7'
          ports:
            - containerPort: 8545
              name: rpc
            - containerPort: 30301
              name: udp
              protocol: UDP
            - containerPort: 30303
              name: ipc
              protocol: UDP
          command:
            - bootnode
          args:
            - '--nodekey=/opt/bootnode/boot.key'
            - '--verbosity=9'
          volumeMounts:
            - name: bootkey
              mountPath: /opt/bootnode
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 250Mi
      volumes:
        - name: bootkey
          secret:
            secretName: bootkey
---
kind: Service
apiVersion: v1
metadata:
  name: bootnode
spec:
  selector:
    component: bootnode
  ports:
    - port: 8545
      targetPort: 8545
      name: rpc
      protocol: TCP
    - port: 30301
      targetPort: 30301
      name: udp
      protocol: UDP
    - port: 30303
      targetPort: 30303
      name: ipc
      protocol: UDP
